-- ============================================================
-- MovieBot — CORRECTED & COMPLETE Supabase Schema
-- Run this in your Supabase SQL Editor to fix all empty tables
-- ============================================================

-- ── 1. SESSIONS ─────────────────────────────────────────────
-- FIX: Added missing overflow_buffer_json column
create table if not exists public.sessions (
    chat_id               text primary key,
    session_state         text        not null default 'idle',
    question_index        integer     not null default 0,
    pending_question      text        not null default '',
    answers_mood          text        not null default '',
    answers_genre         text        not null default '',
    answers_language      text        not null default '',
    answers_era           text        not null default '',
    answers_context       text        not null default '',
    answers_time          text        not null default '',
    answers_avoid         text        not null default '',
    answers_favorites     text        not null default '',
    last_question_msg_id  bigint,
    last_recs_json        text        not null default '[]',
    overflow_buffer_json  text        not null default '[]',  -- ← ADDED (was missing)
    sim_depth             integer     not null default 0,
    last_active           timestamptz,
    updated_at            timestamptz not null default now()
);

-- If table already exists, add the missing column:
alter table public.sessions
    add column if not exists overflow_buffer_json text not null default '[]';


-- ── 2. USERS ────────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.users (
    chat_id                text primary key,
    username               text    not null default '',
    preferred_genres       text    not null default '',
    disliked_genres        text    not null default '',
    preferred_language     text    not null default '',
    preferred_era          text    not null default '',
    watch_context          text    not null default '',
    avg_rating_preference  numeric,
    updated_at             timestamptz not null default now()
);


-- ── 3. HISTORY ──────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.history (
    id              bigint generated by default as identity primary key,
    chat_id         text        not null,
    movie_id        text        not null,
    title           text        not null default '',
    year            text        not null default '',
    genres          text        not null default '',
    language        text        not null default '',
    rating          text        not null default '',
    description     text        not null default '',
    director        text        not null default '',
    actors          text        not null default '',
    poster_url      text        not null default '',
    trailer_url     text        not null default '',
    streaming_info  text        not null default '',
    recommended_at  timestamptz not null default now(),
    watched         boolean     not null default false,
    watched_at      timestamptz,
    unique (chat_id, movie_id)
);

create index if not exists idx_history_chat_id          on public.history (chat_id);
create index if not exists idx_history_chat_movie       on public.history (chat_id, movie_id);
create index if not exists idx_history_chat_recommended on public.history (chat_id, recommended_at desc);


-- ── 4. WATCHLIST ─────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.watchlist (
    id              bigint generated by default as identity primary key,
    chat_id         text        not null,
    movie_id        text        not null,
    title           text        not null default '',
    year            text        not null default '',
    language        text        not null default '',
    rating          text        not null default '',
    genres          text        not null default '',
    description     text        not null default '',
    director        text        not null default '',
    actors          text        not null default '',
    poster_url      text        not null default '',
    trailer_url     text        not null default '',
    streaming_info  text        not null default '',
    added_at        timestamptz not null default now(),
    unique (chat_id, movie_id)
);

create index if not exists idx_watchlist_chat_id on public.watchlist (chat_id);


-- ── 5. TRAILER CACHE ─────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.trailer_cache (
    movie_id    text primary key,
    trailer_url text        not null,
    cached_at   timestamptz not null default now()
);


-- ── 6. ADMINS ────────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.admins (
    chat_id          text primary key,
    username         text        not null default '',
    permission_level text        not null default 'admin',
    added_at         timestamptz not null default now()
);


-- ── 7. BOT STATS ─────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.bot_stats (
    metric_name  text primary key,
    metric_value bigint      not null default 0,
    updated_at   timestamptz not null default now()
);


-- ── 8. PROVIDER HEALTH ──────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.provider_health (
    provider_name   text primary key,
    is_enabled      boolean     not null default true,
    failure_count   integer     not null default 0,
    last_failure_at timestamptz,
    updated_at      timestamptz not null default now()
);


-- ── 9. ADMIN AUDIT ──────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.admin_audit (
    id             bigint generated by default as identity primary key,
    timestamp      timestamptz not null default now(),
    admin_chat_id  text        not null,
    command        text        not null,
    details        text        not null default ''
);

create index if not exists idx_admin_audit_timestamp on public.admin_audit (timestamp desc);


-- ── 10. ERROR LOGS ───────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.error_logs (
    id                bigint generated by default as identity primary key,
    timestamp         timestamptz not null default now(),
    chat_id           text        not null default '',
    workflow_step     text        not null default '',
    intent            text        not null default '',
    error_type        text        not null default '',
    error_message     text        not null default '',
    raw_payload       text        not null default '',
    retry_status      text        not null default '',
    resolution_status text        not null default ''
);

create index if not exists idx_error_logs_timestamp on public.error_logs (timestamp desc);
create index if not exists idx_error_logs_type      on public.error_logs (error_type);


-- ── 11. FEEDBACK ─────────────────────────────────────────────
-- FIX: Added UNIQUE(chat_id, movie_id) — required for ON CONFLICT upsert
create table if not exists public.feedback (
    id            bigint generated by default as identity primary key,
    chat_id       text        not null,
    movie_id      text        not null,
    reaction_type text        not null,  -- 'like' or 'dislike'
    timestamp     timestamptz not null default now(),
    unique (chat_id, movie_id)           -- ← ADDED (was missing, broke all upserts)
);

-- If table already exists, add the missing constraint:
alter table public.feedback
    drop constraint if exists feedback_chat_id_movie_id_key;
alter table public.feedback
    add constraint feedback_chat_id_movie_id_key unique (chat_id, movie_id);

create index if not exists idx_feedback_chat_id on public.feedback (chat_id);


-- ── 12. API USAGE ────────────────────────────────────────────
-- No changes needed — fully matches implementation
create table if not exists public.api_usage (
    id                bigint generated by default as identity primary key,
    chat_id           text    not null,
    provider          text    not null,
    action            text    not null,
    timestamp         timestamptz not null default now(),
    prompt_tokens     integer not null default 0,
    completion_tokens integer not null default 0,
    total_tokens      integer not null default 0
);


-- ── 13. USER INTERACTIONS ───────────────────────────────────
-- FIX: Added request_id column — code sends this field, missing column
--      caused HTTP 400 on every insert → table stayed completely empty
create table if not exists public.user_interactions (
    id          bigint generated by default as identity primary key,
    chat_id     text        not null,
    username    text        not null default '',
    input_text  text        not null default '',
    intent      text        not null default '',
    request_id  text,                           -- ← ADDED (was missing, broke all inserts)
    response_status text    not null default 'pending', -- ← ADDED
    latency_ms  integer,                        -- ← ADDED
    error_message text,                         -- ← ADDED
    timestamp   timestamptz not null default now()
);

-- If table already exists, add the missing columns:
alter table public.user_interactions
    add column if not exists request_id text,
    add column if not exists response_status text not null default 'pending',
    add column if not exists latency_ms integer,
    add column if not exists error_message text;

create index if not exists idx_user_interactions_chat_id on public.user_interactions (chat_id);


-- ── SEED DATA ────────────────────────────────────────────────
insert into public.admins (chat_id, username, permission_level)
values ('1878846631', 'Primary Admin', 'super_admin')
on conflict (chat_id) do nothing;

-- Seed initial bot_stats counters so they exist for increment_stat()
insert into public.bot_stats (metric_name, metric_value) values
    ('total_sessions',        0),
    ('total_recommendations', 0),
    ('total_lookups',         0),
    ('total_events',          0)
on conflict (metric_name) do nothing;

-- Seed provider health rows
insert into public.provider_health (provider_name, is_enabled, failure_count) values
    ('perplexity', true, 0),
    ('omdb',       true, 0),
    ('trailers',   true, 0),
    ('watchmode',  true, 0)
on conflict (provider_name) do nothing;
